### ISSUE TITLE
Missing dependency for luci-app-natflow-users

### ISSUE THREAD

**Issue by romanovj** [x-wrt/com.x-wrt#16]
Please add +luci-compat

**Comment by ptpt52** [comment]
why need it?

**Comment by romanovj** [comment]
> why need it?

Isn't working without it. 

I'm importing yours hwnat patches, natflow  and luci-app-natflow-users into my own openwrt tree with Linux 6.9.3 kernel for ramips/mt7621. Others packages like [luci-app-natcap](https://github.com/x-wrt/com.x-wrt/tree/master/luci-app-natcap) have `+luci-compat`.

```
RPCError
RPC call to luci.natflow/get_users failed with error -32000: Object not found
  at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=24.151.81452~b93ee9d:11:3)
```

**Comment by ptpt52** [comment]
fixed in https://github.com/x-wrt/com.x-wrt/commit/f7b419f76d11610c45a999be2ed88894a0e51345
