### ISSUE TITLE
编译时应如何操作，可以使固件具备部署到vps的能力？

### ISSUE THREAD

**Issue by esirplayground** [x-wrt/com.x-wrt#3]
按照blog中的方法，已经将固件成功部署到谷歌云，但是网站下载的现成固件无法扩展功能，自定义固件又不知方法，谢谢！

**Comment by ptpt52** [comment]
你自己去编译

**Comment by ptpt52** [comment]
编译教程 https://blog.x-wrt.com/docs/build/
用模版配置编译就可以vps部署。
